module.exports = {
  proposal: {
    slug: 'proposal',
    label: 'Project Proposal',
    category: 'proposals',
    description: 'Executive-ready proposal with scope, timeline, investment, and next steps.',
    legalDisclaimer: false,
    badgeColor: { bg: '#fef3e2', text: '#92400e' },
    requiredFields: [
      { key: 'client', label: 'Client / Company', type: 'text', placeholder: 'Acme Corp' },
      { key: 'project', label: 'Project Description', type: 'text', placeholder: 'ERP implementation' },
    ],
    optionalFields: [
      { key: 'budget', label: 'Budget Range', type: 'currency', placeholder: '$25,000–$40,000' },
      { key: 'sender', label: 'Prepared By', type: 'text', placeholder: 'Jane Smith, Apex Consulting' },
      { key: 'notes', label: 'Key Details', type: 'textarea', placeholder: 'Timeline, deliverables, special requirements...' },
    ],
    outputStructure: ['Executive Summary', 'Problem Statement', 'Proposed Approach', 'Deliverables', 'Timeline', 'Investment', 'Team', 'Next Steps'],
    systemPromptAddition: 'Produce a formal executive-ready proposal. Lead with outcomes. Include a concise deliverables table and phased timeline. Investment section must include line-item breakdown.',
  },

  sow: {
    slug: 'sow',
    label: 'Statement of Work',
    category: 'proposals',
    description: 'Detailed SOW with deliverables table, milestones, acceptance criteria, and change order procedure.',
    legalDisclaimer: false,
    badgeColor: { bg: '#e8eaf6', text: '#1a237e' },
    requiredFields: [
      { key: 'client', label: 'Client / Company', type: 'text', placeholder: 'Meridian Corp' },
      { key: 'project', label: 'Project / Engagement Name', type: 'text', placeholder: 'Q3 Data Migration' },
      { key: 'serviceProvider', label: 'Service Provider', type: 'text', placeholder: 'Apex IT Solutions' },
    ],
    optionalFields: [
      { key: 'startDate', label: 'Estimated Start Date', type: 'date', placeholder: '' },
      { key: 'budget', label: 'Total Project Fee', type: 'currency', placeholder: '$18,000' },
      { key: 'deliverables', label: 'Key Deliverables', type: 'multiline-list', placeholder: 'One deliverable per line' },
      { key: 'notes', label: 'Additional Scope Notes', type: 'textarea', placeholder: '' },
    ],
    outputStructure: ['Parties', 'Project Overview', 'Scope of Work', 'Deliverables', 'Milestone Schedule', 'Acceptance Criteria', 'Change Order Procedure', 'Investment & Payment', 'Confidentiality', 'Signatures'],
    systemPromptAddition: 'Format Deliverables as a structured table (Deliverable | Due Date | Acceptance Criteria). Number all milestones. Include a clear change order procedure clause.',
  },

  rfp: {
    slug: 'rfp',
    label: 'RFP Response',
    category: 'proposals',
    description: 'Formal response to a Request for Proposal with required section structure.',
    legalDisclaimer: false,
    badgeColor: { bg: '#e8f5e9', text: '#1b5e20' },
    requiredFields: [
      { key: 'issuingOrg', label: 'Issuing Organization', type: 'text', placeholder: 'State of Ohio DOT' },
      { key: 'rfpReference', label: 'RFP Reference Number', type: 'text', placeholder: 'RFP-2024-0042' },
      { key: 'proposingOrg', label: 'Proposing Organization', type: 'text', placeholder: 'Apex Consulting Group' },
      { key: 'solutionSummary', label: 'Proposed Solution Summary', type: 'textarea', placeholder: 'Brief description of your approach...' },
    ],
    optionalFields: [
      { key: 'submissionDeadline', label: 'Submission Deadline', type: 'date', placeholder: '' },
      { key: 'pricingApproach', label: 'Pricing Approach', type: 'textarea', placeholder: 'Fixed fee, T&M, milestone-based...' },
      { key: 'teamComposition', label: 'Team Composition', type: 'textarea', placeholder: 'Key roles and personnel...' },
      { key: 'requiredSections', label: 'Required Response Sections', type: 'multiline-list', placeholder: 'One required section per line (from the RFP)' },
    ],
    outputStructure: ['Cover Letter', 'Executive Summary', 'Understanding of Requirements', 'Proposed Solution', 'Technical Approach', 'Team & Qualifications', 'Project Timeline', 'Pricing', 'References', 'Appendices'],
    systemPromptAddition: 'Structure the response to directly address each required section from the RFP. Use formal government/enterprise proposal conventions. Begin with a formal cover letter. Pricing section must be clear and itemized.',
  },

  'change-order': {
    slug: 'change-order',
    label: 'Change Order',
    category: 'governance',
    description: 'Formal amendment documenting scope changes, pricing adjustments, and timeline shifts.',
    legalDisclaimer: false,
    badgeColor: { bg: '#fff3e0', text: '#e65100' },
    requiredFields: [
      { key: 'client', label: 'Client / Company', type: 'text', placeholder: 'Acme Corp' },
      { key: 'serviceProvider', label: 'Service Provider', type: 'text', placeholder: 'Apex Consulting' },
      { key: 'originalDoc', label: 'Original Document Reference', type: 'text', placeholder: 'SOW-2024-003 dated Jan 15, 2024' },
      { key: 'changeDescription', label: 'Description of Change', type: 'textarea', placeholder: 'What is changing and why...' },
    ],
    optionalFields: [
      { key: 'priceAdjustment', label: 'Price Adjustment', type: 'currency', placeholder: '+$4,500 or -$1,200' },
      { key: 'timelineAdjustment', label: 'Timeline Adjustment', type: 'text', placeholder: 'e.g. +2 weeks, new completion date March 1' },
      { key: 'reason', label: 'Reason for Change', type: 'textarea', placeholder: '' },
    ],
    outputStructure: ['Change Order Header', 'Reference Documents', 'Description of Change', 'Scope Impact', 'Price Adjustment', 'Timeline Adjustment', 'Approvals & Signatures'],
    systemPromptAddition: 'Use formal change order conventions. Include CO number (CO-001 as default). Reference original document precisely. Approval signatures section must include date fields for both parties.',
  },

  nda: {
    slug: 'nda',
    label: 'Non-Disclosure Agreement',
    category: 'contracts',
    description: 'Mutual or one-way confidentiality agreement with customizable terms.',
    legalDisclaimer: true,
    badgeColor: { bg: '#fce4ec', text: '#880e4f' },
    requiredFields: [
      { key: 'disclosingParty', label: 'Disclosing Party', type: 'text', placeholder: 'Acme Corp, a Delaware corporation' },
      { key: 'receivingParty', label: 'Receiving Party', type: 'text', placeholder: 'Partner LLC, a Texas LLC' },
      { key: 'effectiveDate', label: 'Effective Date', type: 'date', placeholder: '' },
      { key: 'jurisdiction', label: 'Governing Law / Jurisdiction', type: 'text', placeholder: 'State of Delaware' },
      { key: 'ndaType', label: 'Agreement Type', type: 'select', options: ['Mutual', 'One-Way (Disclosing → Receiving)'], placeholder: '' },
    ],
    optionalFields: [
      { key: 'termLength', label: 'Term Length', type: 'text', placeholder: 'e.g. 2 years from Effective Date' },
      { key: 'purpose', label: 'Purpose / Business Context', type: 'textarea', placeholder: 'Evaluation of a potential software development partnership' },
    ],
    outputStructure: ['Parties', 'Recitals & Purpose', 'Definition of Confidential Information', 'Obligations of Receiving Party', 'Exclusions', 'Term & Termination', 'Return of Information', 'Remedies', 'General Provisions', 'Signature Block'],
    systemPromptAddition: 'Use standard NDA legal conventions. Number all clauses (1.1, 1.2, etc.). If mutual, include reciprocal obligations for both parties. Include standard exclusions (publicly available, independently developed, required by law). Signature block must have lines for name, title, date for both parties.',
  },

  msa: {
    slug: 'msa',
    label: 'Master Service Agreement',
    category: 'contracts',
    description: 'Overarching contract framework covering payment, IP, confidentiality, and termination.',
    legalDisclaimer: true,
    badgeColor: { bg: '#ede7f6', text: '#311b92' },
    requiredFields: [
      { key: 'client', label: 'Client / Company', type: 'text', placeholder: 'Acme Corp' },
      { key: 'serviceProvider', label: 'Service Provider', type: 'text', placeholder: 'Apex Solutions LLC' },
      { key: 'effectiveDate', label: 'Effective Date', type: 'date', placeholder: '' },
      { key: 'jurisdiction', label: 'Governing Law / Jurisdiction', type: 'text', placeholder: 'State of New York' },
    ],
    optionalFields: [
      { key: 'paymentTerms', label: 'Payment Terms', type: 'text', placeholder: 'Net 30' },
      { key: 'serviceDescription', label: 'General Services Description', type: 'textarea', placeholder: 'IT consulting, software development, and related services' },
      { key: 'limitOfLiability', label: 'Limitation of Liability', type: 'text', placeholder: 'Total fees paid in prior 12 months' },
    ],
    outputStructure: ['Parties & Effective Date', 'Services', 'Fees & Payment', 'Intellectual Property', 'Confidentiality', 'Warranties & Representations', 'Limitation of Liability', 'Indemnification', 'Term & Termination', 'General Provisions', 'Signature Block'],
    systemPromptAddition: 'Use standard MSA conventions for B2B service engagements. Number all sections and subsections. IP section must address work-for-hire vs. retained IP. Include SOW attachment reference language. Termination section must address for-cause and convenience termination.',
  },

  sla: {
    slug: 'sla',
    label: 'Service Level Agreement',
    category: 'governance',
    description: 'Uptime guarantees, response times, escalation procedures, and remedy structures.',
    legalDisclaimer: false,
    badgeColor: { bg: '#e0f2f1', text: '#004d40' },
    requiredFields: [
      { key: 'client', label: 'Client / Company', type: 'text', placeholder: 'Acme Corp' },
      { key: 'serviceProvider', label: 'Service Provider', type: 'text', placeholder: 'Apex IT Solutions' },
      { key: 'serviceDescription', label: 'Services Covered', type: 'textarea', placeholder: 'Managed IT support, helpdesk, network monitoring' },
    ],
    optionalFields: [
      { key: 'uptimeTarget', label: 'Uptime Target', type: 'text', placeholder: '99.5% monthly' },
      { key: 'responseTime', label: 'Response Time Targets', type: 'textarea', placeholder: 'Critical: 1hr, High: 4hr, Medium: 8hr, Low: 24hr' },
      { key: 'supportHours', label: 'Support Hours', type: 'text', placeholder: 'Mon–Fri 8am–6pm EST, 24/7 for critical' },
      { key: 'remedies', label: 'Remedy / Credit Structure', type: 'textarea', placeholder: 'Service credits as % of monthly fee if SLA is breached' },
    ],
    outputStructure: ['Parties & Scope', 'Service Descriptions', 'Availability & Uptime Targets', 'Incident Response Times', 'Escalation Procedure', 'Scheduled Maintenance', 'Reporting & Review', 'Remedies & Service Credits', 'Exclusions', 'Review & Amendment'],
    systemPromptAddition: 'Format response time targets as a clear table (Priority | Response Time | Resolution Target). Include a numeric incident priority matrix. Remedy structure must specify credit calculation method. Exclude force majeure events explicitly.',
  },

  'vendor-agreement': {
    slug: 'vendor-agreement',
    label: 'Vendor / Contractor Agreement',
    category: 'contracts',
    description: 'Formal engagement contract for hiring subcontractors or vendors.',
    legalDisclaimer: true,
    badgeColor: { bg: '#f3e5f5', text: '#4a148c' },
    requiredFields: [
      { key: 'hiringParty', label: 'Hiring Party', type: 'text', placeholder: 'Apex Agency LLC' },
      { key: 'vendor', label: 'Vendor / Contractor', type: 'text', placeholder: 'Jane Doe d/b/a JD Design' },
      { key: 'serviceDescription', label: 'Services to Be Performed', type: 'textarea', placeholder: 'UI/UX design for mobile application...' },
      { key: 'effectiveDate', label: 'Effective Date', type: 'date', placeholder: '' },
      { key: 'jurisdiction', label: 'Governing Law', type: 'text', placeholder: 'State of California' },
    ],
    optionalFields: [
      { key: 'compensation', label: 'Compensation', type: 'text', placeholder: '$5,000 fixed / $120/hr' },
      { key: 'termLength', label: 'Term', type: 'text', placeholder: 'Project-based or through Dec 31, 2025' },
      { key: 'deliverables', label: 'Key Deliverables', type: 'multiline-list', placeholder: 'One deliverable per line' },
    ],
    outputStructure: ['Parties', 'Services & Deliverables', 'Compensation & Payment', 'Independent Contractor Status', 'Intellectual Property', 'Confidentiality', 'Term & Termination', 'Indemnification', 'General Provisions', 'Signature Block'],
    systemPromptAddition: 'Include a clear independent contractor (not employee) clause with relevant IRS criteria. IP assignment should favor the hiring party. Include standard non-solicitation clause. Signature block must have full legal name, title, and date lines for both parties.',
  },

  'capability-statement': {
    slug: 'capability-statement',
    label: 'Capability Statement',
    category: 'proposals',
    description: 'B2B sales and vendor onboarding document: core competencies, differentiators, past performance.',
    legalDisclaimer: false,
    badgeColor: { bg: '#e8f5e9', text: '#2e7d32' },
    requiredFields: [
      { key: 'companyName', label: 'Company Name', type: 'text', placeholder: 'Apex Consulting Group' },
      { key: 'coreCapabilities', label: 'Core Capabilities / Services', type: 'multiline-list', placeholder: 'One capability per line' },
      { key: 'targetAudience', label: 'Target Client / Industry', type: 'text', placeholder: 'Federal agencies, Fortune 500, healthcare systems' },
    ],
    optionalFields: [
      { key: 'differentiators', label: 'Key Differentiators', type: 'multiline-list', placeholder: 'One differentiator per line' },
      { key: 'pastPerformance', label: 'Past Performance / Notable Clients', type: 'textarea', placeholder: 'Client | Project | Scope | Outcome' },
      { key: 'certifications', label: 'Certifications / NAICS Codes', type: 'text', placeholder: 'ISO 9001, NAICS 541512' },
      { key: 'contactInfo', label: 'Primary Contact Info', type: 'textarea', placeholder: 'Name, title, email, phone' },
    ],
    outputStructure: ['Company Overview', 'Core Competencies', 'Differentiators', 'Past Performance', 'Certifications & Credentials', 'Contact Information'],
    systemPromptAddition: 'Format as a one-to-two page business capability statement. Use bullet points for capabilities and differentiators. Past performance section should follow CPAR-style formatting (Client | Project | Scope | Outcome). Keep language active and results-oriented.',
  },

  'project-closeout': {
    slug: 'project-closeout',
    label: 'Project Closeout Document',
    category: 'closeout',
    description: 'Formal end-of-engagement summary with deliverables inventory, handoff notes, and sign-off.',
    legalDisclaimer: false,
    badgeColor: { bg: '#efebe9', text: '#4e342e' },
    requiredFields: [
      { key: 'client', label: 'Client / Company', type: 'text', placeholder: 'Acme Corp' },
      { key: 'projectName', label: 'Project Name', type: 'text', placeholder: 'Q3 ERP Migration' },
      { key: 'serviceProvider', label: 'Service Provider', type: 'text', placeholder: 'Apex IT Solutions' },
      { key: 'completionDate', label: 'Completion Date', type: 'date', placeholder: '' },
    ],
    optionalFields: [
      { key: 'deliverables', label: 'Deliverables Inventory', type: 'multiline-list', placeholder: 'List each delivered item' },
      { key: 'outstandingItems', label: 'Outstanding Items / Open Issues', type: 'textarea', placeholder: 'Any unresolved items, follow-ups...' },
      { key: 'knowledgeTransfer', label: 'Knowledge Transfer Notes', type: 'textarea', placeholder: 'System access, documentation location, key contacts...' },
      { key: 'lessonsLearned', label: 'Lessons Learned', type: 'textarea', placeholder: 'What went well, what to improve next time...' },
    ],
    outputStructure: ['Project Summary', 'Deliverables Inventory', 'Quality Verification', 'Outstanding Items', 'Knowledge Transfer', 'Lessons Learned', 'Client Feedback', 'Sign-Off & Acceptance'],
    systemPromptAddition: 'Format deliverables as a numbered checklist with status column (Delivered / Accepted). Sign-off section must include formal acceptance language and signature lines for both parties. Outstanding items formatted as a table: Item | Owner | Due Date.',
  },
};
